### ISSUE TITLE
post with data

### ISSUE THREAD

**Issue by milovanderlinden** [peter-vdc/nodeunit-express#4]
Hi there,

I am really enjoying your nodeunit-express helping my unittesting an awful lot, thank you!

I have been trying for three days to get a post with data working. Do you have an example of posting with data? Or do I have to use tester.js, to do that?

**Comment by peter-vdc** [comment]
Hi Milo,

Tester.js was not written by myself, but was a contribution to this
project. It's another way of using nodeunit-express, making it more
readable (checkout the sample in /test/tester.js - it also contains a post
example).

I'm not sure what is going wrong with your POST tests. First you need to
'set' your headers and 'write' your post data. after that you can do the
'post'.

Kind regards,
Peter Vandercappellen

**Comment by milovanderlinden** [comment]
Hello Peter,

Thnank you for the response. Unfortunately, due to pressure on my project I decided to move to mocha and managed to fix my problems last weekend.

**Comment by darkpixel** [comment]
Yeah, there doesn't appear to be a way to simulate POSTing data (i.e. creating a custom request object) so a lot of the functions called by routers will break.
